### ISSUE TITLE
Psi+ (webkit,qt5) windows positioning drift

### ISSUE THREAD

**Issue by aptem-v** [psi-im/psi#281] opened 2017-06-04 09:57 UTC
Tested with OpenBox and XFWM4 window managers.

On Psi+ exit, it saves roster and chats (separated) windows positions relatively to WM decorations.
And then, on start, it resores windows positions relatively to windows content.

As a result, from start by start, the roster window drifts, and it's X and Y coordinates gradually decreases by the width of the WM decorations, and stops only when the contents(OpenBox) or decorations (XFWM4) of the window reached the top and left border of screen.

Psi+ 1.0.10, 1.0.11 from git (webkit, Qt5) was builded in last Arch Linux, i686/x86_64, GCC-7.

**Comment by wadealer** [comment] 2017-06-04 12:39
This is the known bug and afaik it relates to Qt. It reproduces on some WMs on linux only.

**Comment by aptem-v** [comment] 2017-06-04 14:22
But it not reproduces in the old Qt4 Psi+, also no this bug in other Qt5 interfaces, like VirtualBox GUI or transmission-qt.

I will try to find about Qt5 windows positioning problems...

**Comment by aptem-v** [comment] 2017-06-04 18:44
I have studied the question.
The problem is not specific to Qt5, the fact is that in X11 it is required to save and restore the internal geometry of the window, because the external geometry depends on the WM adding decorations asynchronously, already after the window was created.

Accodring to this,
[http://doc.qt.io/qt-5/application-windows.html#window-geometry](http://doc.qt.io/qt-5/application-windows.html#window-geometry)
we need to save, for example, `QMainWindow::geometry()` and restore by `QMainWindow::setGeometry()`

I was tested it on the small dummy program, and it works.

**Comment by Ri0n** [comment] 2017-06-06 09:34
it seems our code for some reason does not use technique described here http://doc.qt.io/qt-5/restoring-geometry.html. But it was used before. I don't see any comments on this in the code but something about reverting.

Currently it saves widget's normalGeometry and frameGeometry as well as some other parameters.
And to restore it builds QByteArray suitable for restoreGeometry.

see advwidget.cpp for details.

**Comment by Vitozz** [comment] 2018-05-21 13:43
> it seems our code for some reason does not use technique described here http://doc.qt.io/qt-5/restoring-geometry.html.

text from this document:
On X11, this might not work because an invisible window does not have a frame yet. The window manager will decorate the window later. When this happens, the window shifts towards the bottom/right corner of the screen depending on the size of the decoration frame. Although X provides a way to avoid this shift, some window managers fail to implement this feature.

It depends on WM, maybe that's why we do not use this tehnique

**Comment by aptem-v** [comment] 2018-09-06 08:09
It turn much worse in version 1.3: undecorated windows not supported anymore, and no way to avoid drift.

**Comment by Vitozz** [comment] 2018-09-08 22:54
if I'm not mistaken, in xfwm everything is now tied to gtk3 and unfortunately the gtk3 policy does not allow qt applications to disable window decorations in normal way.

**Comment by aptem-v** [comment] 2018-09-09 07:33
It is not depend on WM.
I'm using OpenBox, tried Xfwm4 and Kwin, but result is same: Psi-1.3 can't undecorate windows anymore.
And No, it is not OpenBox's bug – Psi windows drifting under Kwin too.

**Comment by Vitozz** [comment] 2018-09-09 17:04
I use plasma and I have no such problems. But when I used xfce or mate, I also had similar behavior.

**Comment by aptem-v** [comment] 2018-12-14 17:36
FInally, after Qt update from 5.11 to 5.12, Psi began to restore the window position, adjusted for the decorations width.
Tested on OpenBox and xfwm.
It works with caution: Even if decorations disabled for this Psi by WM, position will be restored, like as decirations exists.

**Comment by Ri0n** [comment] 2018-12-14 17:50
hurray! finally not we fixed it!

**Comment by tehnick** [comment] 2019-03-04 10:37
Should we close this issue?

**Comment by Ri0n** [comment] 2019-03-04 11:07
> Should we close this issue?

I'm ok with it

**Closed** 2019-03-04 11:08 UTC
