### ISSUE TITLE
futex hang with actual HEAD when starting

### ISSUE THREAD

**Issue by mowgli** [psi-im/psi#743] opened 2024-03-17 18:08 UTC
Current Version does block in futex when starting, Version 1.5-1653 does work fine.

*OS:* Gentoo

*Psi Version:* HEAD

XML log (you can find it in account's context menu)
Does not apply, startup failed

stdout (terminal log)
```
```
(That is currently the output: Nothing!

In case of app crash please provide back trace (start debug version in gdb).
No crash, it hangs forever

I have a strace of a hanging one. Going back to the version of begin this year works well.

**Comment by Neustradamus** [comment] 2024-03-19 12:19
@Ri0n: What do you think?

**Comment by Ri0n** [comment] 2024-03-19 12:52
Current Version == master?

**Comment by Ri0n** [comment] 2024-03-19 12:56
I'm on Gentoo too and another dev on arch. 
both qt5 and qt6 versions with and without webengine start fine. 
so I really need to know more details. 
Like how it was compiled, which flags, which USE flags. Is it rion-overlay or not.

**Comment by Ri0n** [comment] 2024-03-19 14:18
hm but it reminds me qca problem.
I build from my overlay (rion-overlay). It has bundled QCA with some fixes, which upstream doesn't want to accept. 
One of the fixes was for similar issue. 
It's easy to checked if it's the case with  psi from portage (not overlay). Just rebuild QCA without gpg support. If it starts well, then that's the case.

**Comment by mowgli** [comment] 2024-03-19 17:53
Hi,

I have strace log and, maybe of interest, binpkgs of the broken ones.

As I told, it is master HEAD, so version 9999. It is from the rion
overlay with the following use flags: dbus extras hunspell iconsets
xscreensaver -aspell -debug -doc -enchant -keyring -webengine (However,
I also have a broken version as binpkg without dbus flag.)

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen ***@***.***>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by Ri0n** [comment] 2024-03-19 21:25
I couldn't reproduce it with same flags. 
yes, strace probably would be useful

**Comment by Ri0n** [comment] 2024-03-19 22:31
I just checked my overlay's ebuild. It was broken. it still was using system broken QCA because we changed options' names.
I updated the ebuild in my overlay

**Comment by Ri0n** [comment] 2024-03-21 13:20
Is this still reproducible with the latest master and updated overlay?

**Comment by Neustradamus** [comment] 2024-03-22 19:17
@mowgli: Have you seen @Ri0n comments?

**Comment by mowgli** [comment] 2024-03-22 19:43
Am Fr den 22. Mär 2024 um 20:17 schrieb Neustradamus:
> @mowgli: Have you seen @Ri0n comments?

You mean the one of Sergei about asking for test?

Yes, but I had no time until now to rebuild it.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen ***@***.***>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by mowgli** [comment] 2024-03-24 09:46
Well, today I was able to test a rebuild. Without success:
~> less /var/tmp/portage/net-im/psi-9999/temp/build.log
 * Package:    net-im/psi-9999:0
 * Repository: rion
 * Maintainer: rion4ik@gmail.com proxy-maint@gentoo.org
 * USE:        X abi_x86_64 amd64 dbus elibc_glibc extras hunspell iconsets kernel_linux
 * FEATURES:   ccache network-sandbox preserve-libs sandbox suidctl userpriv usersandbox
 * You're about to build a branded version of Psi called Psi+.
 * Psi+ patches were fully merged to Psi.
 * The only difference is the name and some artwork.
 * 
 * Some artwork is from open source projects, but some is provided 'as-is'
 * and has not clear licensing.
 * Possibly this build is not redistributable in some countries.
>>> Unpacking source...
 * Repository id: psi-plus_psi-plus-snapshots.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_PSI_PLUS_PSI_PLUS_SNAPSHOTS
 *   EGIT_OVERRIDE_BRANCH_PSI_PLUS_PSI_PLUS_SNAPSHOTS
 *   EGIT_OVERRIDE_COMMIT_PSI_PLUS_PSI_PLUS_SNAPSHOTS
 *   EGIT_OVERRIDE_COMMIT_DATE_PSI_PLUS_PSI_PLUS_SNAPSHOTS
 * 
 * Fetching https://github.com/psi-plus/psi-plus-snapshots.git ...
git fetch https://github.com/psi-plus/psi-plus-snapshots.git +HEAD:refs/git-r3/HEAD
fatal: not a git repository: '/var/cache/distfiles/git3-src/psi-plus_psi-plus-snapshots.git'
 * ERROR: net-im/psi-9999::rion failed (unpack phase):
 *   Unable to fetch from any of EGIT_REPO_URI
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_unpack
 *   environment, line 3007:  Called git-r3_src_unpack
 *   environment, line 2473:  Called git-r3_src_fetch
 *   environment, line 2467:  Called git-r3_fetch
 *   environment, line 2389:  Called die
 * The specific snippet of code:
 *       [[ -n ${success} ]] || die "Unable to fetch from any of EGIT_REPO_URI";
 * 
 * If you need support, post the output of `emerge --info '=net-im/psi-9999::rion'`,
 * the complete build log and the output of `emerge -pqv '=net-im/psi-9999::rion'`.
 * The complete build log is located at '/var/tmp/portage/net-im/psi-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-im/psi-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/net-im/psi-9999/work'
 * S: '/var/tmp/portage/net-im/psi-9999/work/psi-9999'

**Comment by Ri0n** [comment] 2024-03-24 11:11
> fatal: not a git repository: '/var/cache/distfiles/git3-src/psi-plus_psi-plus-snapshots.git'

Looks like local filesystem corruption. You probably need to delete this directory manually and try again.

**Comment by mowgli** [comment] 2024-03-24 11:56
Hi Sergei,

Am So den 24. Mär 2024 um 12:11 schrieb Sergei Ilinykh:
> > fatal: not a git repository: '/var/cache/distfiles/git3-src/psi-plus_psi-plus-snapshots.git'
> 
> Looks like local filesystem corruption. You probably need to delete this directory manually and try again.

Yes, that was the issue. Thanks.

After that, now it built fine and is working.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen ***@***.***>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by Ri0n** [comment] 2024-03-24 12:28
great! thanks! 
a few plugins are still broken on Wayland. but there are no other critical errors AFAIK.
closing this one..

**Closed by Ri0n** 2024-03-24 12:28 UTC
Labels: bug
