### ISSUE TITLE
[FreeBSD] problem with DNS resolver from Qt

### ISSUE THREAD

**Issue by xexio** [psi-im/psi#425] opened 2019-02-01 20:54 UTC
I can't connect to any server with Psi in FreeBSD.

The console show: Unknown signature value:  795 (unknown:0, unknown)

**Comment by Ri0n** [comment] 2019-02-01 20:56
ensure qca-ossl plugin is installed and loaded. 
You can find security plugins diagnostics from main menu > help

**Comment by Ri0n** [comment] 2019-02-02 08:32
Ah good. Then if xml console outputs nothing, likely it's a problem with Qt's internal service resolver.
Tcpdump for dns and xmpp would be useful too

**Comment by drook** [comment] 2019-02-06 10:14
I have what seems to be exactly the same problem. I've been using psi 0.15 I believe, and after the upgrade to the 1.3 I got this. The funny thing is, that psi doesn't even try to resolve the target host (so no attempt to connect to tcp/5222/5223 is made), but if it's entered manually in profile connection's properties - I mean it's IP - then it connects just fine.

It's clearly the problem with the resolver, but I was under impression that Qt should use the system one (which in mys case works just fine).

**Comment by arrowd** [comment] 2019-02-06 10:16
I have this problem with `jabber.mipt.ru` server, however Psi successfully connects to another private Jabber I'm using. I wasn't able to figure out what's difference between them. Both are using certificates and I use DNS names to connect to both of them.

**Comment by tehnick** [comment] 2019-02-06 11:08
> The funny thing is, that psi doesn't even try to resolve the target host

By default the internal Qt implementation of DNS resolver is used now. You may try to build program with our old implementation of DNS resolver (`-DUSE_QJDNS=ON` configuration option for `cmake`) and check the difference.

But the preferable solutions would be to find the root of bug and report to Qt developers.

**Comment by tehnick** [comment] 2019-02-06 11:16
> I tried with Kopete, and when I tried to connect to the same server (jabber.es), kopete show a message indicating that Kopete can’t validate the certificate (the certificate it’s with lets encrypt) if I want to continue I need to press the continue button. I pressed the button and Kopete connect correctly.

I saw the same dialog during connection to `jabber.ru` from latest version of Psi+ launched on WinXP when `certs/` subdirectory was removed. So in your case Psi IM should work in a same way.

**Comment by tehnick** [comment] 2019-02-06 11:18
BTW, Psi+ for WinXP is built with `-DUSE_QJDNS=ON`. But I am not sure it is important.

**Comment by xexio** [comment] 2019-02-07 12:07
Ok, I'll try to compile the last version of Psi with the flag -DUSE_QJDNS=ON

> I have what seems to be exactly the same problem. I've been using psi 0.15 I believe, and after the upgrade to the 1.3 I got this. The funny thing is, that psi doesn't even try to resolve the target host (so no attempt to connect to tcp/5222/5223 is made), but if it's entered manually in profile connection's properties - I mean it's IP - then it connects just fine.
> 
> It's clearly the problem with the resolver, but I was under impression that Qt should use the system one (which in mys case works just fine).

How can I do that?

**Comment by tehnick** [comment] 2019-02-07 12:24
> How can I do that?

Menu Common --> Accounts --> Modify --> Connection --> Manually specify Server Host/Port ...

**Comment by xexio** [comment] 2019-02-10 11:52
> > How can I do that?
> 
> Menu Common --> Accounts --> Modify --> Connection --> Manually specify Server Host/Port ...

That don't work in my case, psi output to the console the same error "Unknown signature value"

![image](https://user-images.githubusercontent.com/5065645/52533336-a4eb2780-2d32-11e9-8f98-ad4a44d90ffa.png)

I'm trying to debug Psi, I downloaded the code and imported in Qt Creator to debug it. But shows that error, you know what libraries are missing?

![fail_build](https://user-images.githubusercontent.com/5065645/52533327-8422d200-2d32-11e9-9a81-8475e1147e16.png)

**Comment by Ri0n** [comment] 2019-02-10 13:29
Unknown signature value means dns is resolved successfully, tcp connection is also established and tls started working (usually when client sends starttls via xmpp if account settings are default).
So xml logs would be helpful

**Comment by tehnick** [comment] 2019-02-10 16:15
> That don't work in my case, psi output to the console the same error "Unknown signature value"

Because IPv4 address should be there instead of domain name.

**Comment by tehnick** [comment] 2019-02-19 06:51
@xexio
> Ok, I'll try to compile the last version of Psi with the flag -DUSE_QJDNS=ON

Any results with this?

I have looked into recipe of Psi+ package for Haiku and they use `qjdns` as well.
It looks what native code from Qt works well only on officially supported systems...

**Comment by tehnick** [comment] 2019-03-04 09:01
Ping? I am going to close this issue.

**Comment by xexio** [comment] 2019-03-04 15:06
Sorry, I'll try this week.

**Comment by drook** [comment] 2019-03-05 08:40
Well, the Qt DNS resolver sems to be broken for psi, so please could you explain why are you about to close this ? Should I recreate another ticker mentioning the Qt resolver explicitely ?

**Comment by Ri0n** [comment] 2019-03-05 09:12
I can't find corresponding bug in Qt tracker. Probably we need a minimal reproducible example

**Comment by traumschule** [comment] 2019-04-06 17:57
Same problem with [psi on debian/buster](https://tracker.debian.org/pkg/psi)
>ii  psi            1.3-5        i386         Jabber client using Qt

**Comment by Neustradamus** [comment] 2019-04-15 03:20
Badly Debian "10" Buster has not Psi 1.4 :/
Psi on Debian/Ubuntu is not managed by Psi team.

Maybe if we are many people, Psi can be managed by Psi team in Debian/Ubuntu... for have a perfect Psi in Debian Bullseye "11" in the future and next Ubuntu too.

**Comment by udanieli** [comment] 2019-05-12 00:09
DNS resolver seems broken. If I put the IP address instead of the jabber hostname everything works, otherwise `ConnectionError` appears.

**Comment by Ri0n** [comment] 2019-05-12 06:34
I hope you guys reported this to your distro's tracker too. Becaue @tehnick mentioned Qt resolver works well on officially supported systems. Especially with my recent fix in Psi where I switched to QHostInfo for A and AAAA DNS records which worked well for years.

@traumschule, I did't test socks proxy for years. I'll definitely do that.

**Comment by tehnick** [comment] 2019-05-12 10:23
> Qt resolver works well on officially supported systems.

It works fine even in Haiku now, which is not officially supported. (They have recently added quite simple patch to their port of Qt which fixes this.)

In fact MS Windows XP and FreeBSD (I do not know affected versions) -- the only two systems where native DNS resolver from Qt have issues and Psi should be built with `qjdns` as workaround.

As for MS Windows, WinXP is not supported by Qt developers anymore and in Win7 and newer all work fine. Official support of Qt 5.6.x LTS was stopped at March and we are going to stop support of WinXP in observable future (but not sure how soon through), so FreeBSD will be left the only one system which needs `qjdns`.

And we would like to remove `qjdns` code too because it was written the long time before the necessary functionality was realized in Qt and now its support only wasting time of developers and complicates the codebase.

So the problem should be found and fixed in FreeBSD port of Qt and we finally will be able to remove `qjdns` with relief.

**Comment by udanieli** [comment] 2019-05-13 11:48
> I can't find corresponding bug in Qt tracker. Probably we need a minimal reproducible example

I can't understand which kind of issue this could be. Which method/class of the Qt5 Network framework should fail on FreeBSD during a hostname resolving?

I have compiled the [HTTP Example](https://doc.qt.io/qt-5/qtnetwork-http-example.html), in which requests are made with [`QNetworkAccessManager`](https://doc.qt.io/qt-5/qnetworkaccessmanager.html#details) and [`QNetworkRequest `](https://doc.qt.io/qt-5/qnetworkrequest.html#details) objects and also tested [QHostInfo::lookupHost](https://doc.qt.io/qt-5/qhostinfo.html#lookupHost). In both cases DNS seems to resolve correctly. My workstation runs FreeBSD 12 with standard Qt5 installed from `pkg` static repositories.

I don't have any knowledge of the Psi code so I don't know how to make an example which resembles the Psi behavior: can you point out some relevant code portion to help me look in the right place?

**Comment by Ri0n** [comment] 2019-05-13 12:05
https://github.com/psi-im/iris/blob/9f68056d641a58fd8881b30d1af1813a03ea452b/src/irisnet/corelib/netinterface_qtname.cpp

Basically there are two types of dns lookups. SRV records are resolved with QDnsLookup and A/AAAA with QHostInfo.
If SRV fails it usually fallbacks to A/AAAA records of our jabber server hostname.

some details about SRV in XMPP https://wiki.xmpp.org/web/SRV_Records

**Comment by tehnick** [comment] 2019-05-13 12:31
Just for info, related fix in Qt port from Haiku looks like this:
https://github.com/haikuports/haikuports/blob/722ec61c/dev-qt/qt5/patches/qt5-5.12.3.patchset#L321

As maintainer explained me, he made the same stub as used in Qt port for Android. Before this change Qt used "unix realization" of DnsLookup, which calls `libresolv` (which should be `libnetwork` in case of Haiku) multiple times, loading this library in runtime. After adding of this patch Qt began using native DNS resolver from Haiku and problem with Psi and few other programs was fixed.

Probably in FreeBSD port of Qt may be used the same trick. Please consult with Qt maintainer from FreBSD.

**Comment by arrowd** [comment] 2019-05-13 12:40
> Just for info, related fix in Qt port from Haiku looks like this:
> https://github.com/haikuports/haikuports/blob/722ec61c/dev-qt/qt5/patches/qt5-5.12.3.patchset#L321
> 
> As maintainer explained me, he made the same stub as used in Qt port for Android. Before this change Qt used "unix realization" of DnsLookup, which calls `libresolv` (which should be `libnetwork` in case of Haiku) multiple times, loading this library in runtime. After adding of this patch Qt began using native DNS resolver from Haiku and problem with Psi and few other programs was fixed.
> 
> Probably in FreeBSD port of Qt may be used the same trick. Please consult with Qt maintainer from FreBSD.

I don't quite get it. It stubs an implementation of `QDnsLookup` for haiku. How does stubbing out an implementation fix things?

**Comment by tehnick** [comment] 2019-05-13 13:19
> I don't quite get it. It stubs an implementation of `QDnsLookup` for haiku. How does stubbing out an implementation fix things?

I did not look into this part of Qt code I do not know exactly which kind of magic is used there. I may only suppose that when this first method of DNS lookup is failed Qt uses other (fallback) method with lower priority which does the right thing in case of Haiku **and** Android.

Haiku and Android maintainers of Qt should know more about this trick.

**Comment by arrowd** [comment] 2019-05-14 10:40
I'm one of FreeBSD Qt maintainers, and I'll be happy to take a look at minimal testcase, if you, @udanieli , would be able to come up with.

**Comment by udanieli** [comment] 2019-05-14 13:57
> https://github.com/psi-im/iris/blob/9f68056d641a58fd8881b30d1af1813a03ea452b/src/irisnet/corelib/netinterface_qtname.cpp
> 
> Basically there are two types of dns lookups. SRV records are resolved with QDnsLookup and A/AAAA with QHostInfo.
> If SRV fails it usually fallbacks to A/AAAA records of your jabber server hostname.
>  [...]

Where is this class used in the project? Grepping `IrisQtName` or its methods does not throw any result.

**Comment by Ri0n** [comment] 2019-05-14 14:16
@udanieli, it's in the same file

**Comment by udanieli** [comment] 2019-05-15 06:45
Thank you  @Ri0n. 
There is really a lot of code and encapsulation involving Dns resolvers, I have spent hours grepping and watching at this huge codebase but anyway it does not matter because the problem is in the Qt library, as @tehnick argued.

I wrote a [minimal test app](https://gist.github.com/udanieli/82bac1e415014c71228199ba19b96375) and yes, it fails with _Resolver functions not found_.

So I compiled Qt5 from source to debug the corresponding calls in `src/network/kernel/qdnslookup_unix.cpp` but I had no DNS issues, it worked.
This issue [has been fixed](https://github.com/qt/qtbase/commit/8eeb5150ed99914e252a84f1637f179e3de04659) on April 5  by @davidebeatrici, here is the [corresponding bug on QT](https://bugreports.qt.io/browse/QTBUG-74844). He also did a [small test app](https://github.com/davidebeatrici/qdnslookup_test/blob/master/main.cpp) of course.

**Comment by tehnick** [comment] 2019-05-15 09:12
> This issue [has been fixed](https://github.com/qt/qtbase/commit/8eeb5150ed99914e252a84f1637f179e3de04659) on April 5 by @davidebeatrici, here is the [corresponding bug on QT](https://bugreports.qt.io/browse/QTBUG-74844). He also did a [small test app](https://github.com/davidebeatrici/qdnslookup_test/blob/master/main.cpp) of course.

Great news! So the question now is in backport of this fix by Qt maintainers from FreeBSD into supported versions of FreeBSD.

Could we close this issue in Psi now?

**Comment by arrowd** [comment] 2019-05-15 10:01
Well, It would be great to make sure that this bug is actually the one that we see in Psi. But the chances it is are high, so I'd say, yes, close it.

**Comment by Ri0n** [comment] 2019-05-15 11:06
@arrowd are you going to update Qt in FreeBSD?
I think Psi compilation can be made also kind of conditional (qt/jdns) until we drop support for internal qjdns which is going to happen after 2.0 release.

**Comment by arrowd** [comment] 2019-05-16 14:14
> @arrowd are you going to update Qt in FreeBSD?

Already submitted the change and waiting approval to commit.

**Comment by arrowd** [comment] 2019-05-18 16:25
I've commited that patch from QtNetwork library. People running FreeBSD should make sure to update `qt5-network` package to `5.12.2_1`. This hopefully fixes Psi problem.

**Comment by tehnick** [comment] 2019-05-18 18:17
Excellent! Thanks.

**Closed by tehnick** 2019-05-18 18:17 UTC

**Comment by Neustradamus** [comment] 2019-05-27 12:42
One or more can confirm that it it solved now?

**Comment by xexio** [comment] 2019-05-28 06:16
I'll update and check tonight (spanish hour)
