### ISSUE TITLE
Auto-join in chatrooms doesn't work when signing in

### ISSUE THREAD

**Issue by zak333** [psi-im/psi#339] opened 2018-01-17 08:38 UTC
I have two rooms with auto-join-flag set. When starting Psi 1.3 (self-compiled on linux with latest git 2018-01-05) I am logged into my account after I entered my password. The login succeeds and immediately the dialog for joining the chatrooms opens for each of the rooms. These dialogs then stay open until I cancel them, i.e. joining doesn't finish.
If I open the join-chatrooms-dialog again afterwards, it works immediately.
I recognized an unusual long joining process with versions before (about 20-30 seconds maybe?), but then it always worked at some point.

Is it possible there is some concurrency issue with the login process perhaps?

Let me know if I can provide some more details or log output.

**Comment by Ri0n** [comment] 2018-01-17 09:31
hi
Regarding not finishing dialogs I faced this problem too but was unable to reproduce. It seems it happens when Psi caps are changed and Psi is started with a clean profile. Usually this leads to a lot of incoming disco requests from all the contacts. I tried to get xml log once when it happened and it looked very weird (according to code just impossible)
Long join most likely has the same reason.  A lot of traffic on updating caps.
Besides avatars caching in MUC is not optimized right now. So Psi rerequests avatars from all muc participants on join.

xml logs before dialog cancel and may be even wireshark logs with disabled encryption would be very useful.
You can join our conference psi-dev@conference.jabber.ru to proceed with discussion and testing.

**Comment by Ri0n** [comment] 2018-01-27 18:47
fixed by c05799b50040334947929ac08672a23c193bdec2

**Closed by Ri0n** 2018-01-27 18:47 UTC

**Comment by Ri0n** [comment] 2018-01-27 18:48
the long join is another problem. We already have open issues on the tracker to optimize it.
